### ISSUE TITLE
Hard-coded to your home directory

### ISSUE THREAD

**Issue by with-heart** [hacker-DOM/github-by-stars#1]
This breaks due to the dataset location being hard-coded to your home directory in `src/{getHtmls,sort}.js`. Updating those paths to an existing dir on my machine allows the tool to run.

**Comment by PatMyron** [comment]
https://github.com/dteiml/github-by-stars/blob/f34753e40ab573ac4764d299010e44c953176c82/src/sort.js#L8

https://github.com/dteiml/github-by-stars/blob/f34753e40ab573ac4764d299010e44c953176c82/src/getHtmls.js#L7-L17

---

`github-by-stars $ sed -i '' 's#/Users/dteiml/dev/github-by-stars/##g' src/{getHtmls,sort}.js`

**Comment by dkkb** [comment]
LOL
